"""Thermistor math tests. Standard library unittest — nothing to install.

    python3 -m unittest discover -v

No hardware required, and that's the point: a wrong constant in this chain
produces a *plausible-looking* wrong temperature, which is exactly the bug a
thermal safety tool must never ship.
"""

from __future__ import annotations

import unittest

from sensors.mcp3008 import SimAdc
from sensors.thermistor import ThermistorSensor
from sensors.thermistor_math import (
    ADC_MAX_COUNTS,
    DEFAULT_R_FIXED_OHMS,
    SteinhartCoefficients,
    ThermistorError,
    counts_to_resistance,
    resistance_to_temp_beta,
    resistance_to_temp_steinhart,
    solve_steinhart_hart,
    temp_to_counts,
)


class TestCountsToResistance(unittest.TestCase):
    def test_midscale_equals_fixed_resistor(self):
        """At exactly half scale, the divider is balanced: R_ntc == R_fixed."""
        counts = round(ADC_MAX_COUNTS / 2)
        r = counts_to_resistance(counts)
        self.assertAlmostEqual(r, DEFAULT_R_FIXED_OHMS, delta=30)

    def test_higher_counts_mean_lower_resistance(self):
        """More counts = more voltage at the junction = less NTC resistance
        (which, for an NTC, means hotter)."""
        self.assertLess(
            counts_to_resistance(800),
            counts_to_resistance(300),
        )

    def test_open_circuit_raises(self):
        """0 counts is a disconnected probe, not 'infinitely cold'."""
        with self.assertRaises(ThermistorError):
            counts_to_resistance(0)

    def test_short_circuit_raises(self):
        """Full scale is a short or a missing fixed resistor, not 'infinitely
        hot'. Reporting a temperature here would be inventing data."""
        with self.assertRaises(ThermistorError):
            counts_to_resistance(ADC_MAX_COUNTS)


class TestBetaEquation(unittest.TestCase):
    def test_nominal_resistance_gives_nominal_temp(self):
        """10k on a 10k/25°C thermistor must read exactly 25 °C."""
        self.assertAlmostEqual(resistance_to_temp_beta(10_000.0), 25.0, places=6)

    def test_ntc_is_inverted(self):
        """Negative temperature coefficient: resistance falls as it heats."""
        self.assertGreater(resistance_to_temp_beta(4_000.0), 25.0)
        self.assertLess(resistance_to_temp_beta(30_000.0), 25.0)

    def test_known_datasheet_point(self):
        """A 10k/B3950 NTC is ~3.6 kΩ at 50 °C (datasheet table)."""
        self.assertAlmostEqual(resistance_to_temp_beta(3_600.0), 50.0, delta=1.0)

    def test_non_physical_resistance_raises(self):
        with self.assertRaises(ThermistorError):
            resistance_to_temp_beta(0.0)
        with self.assertRaises(ThermistorError):
            resistance_to_temp_beta(-500.0)


class TestSteinhartHart(unittest.TestCase):
    def _fit_from_beta(self) -> SteinhartCoefficients:
        """Fit coefficients from three points generated by the beta model, so
        the two models must then agree."""
        points = [
            (counts_to_resistance(temp_to_counts(t)), t)
            for t in (0.0, 25.0, 55.0)
        ]
        return solve_steinhart_hart(points)

    def test_fit_reproduces_its_own_calibration_points(self):
        """The defining property: the fitted curve must pass through the three
        points it was built from. calibrate.py gates on exactly this."""
        temps = (0.0, 25.0, 55.0)
        points = [
            (counts_to_resistance(temp_to_counts(t)), t) for t in temps
        ]
        coeffs = solve_steinhart_hart(points)

        for r_ohms, expected_c in points:
            got = resistance_to_temp_steinhart(r_ohms, coeffs)
            self.assertAlmostEqual(got, expected_c, delta=0.05)

    def test_agrees_with_beta_between_calibration_points(self):
        """Interpolating at 40 °C — between the fitted points — must land close
        to the beta model. A wildly different answer means the solve is wrong."""
        coeffs = self._fit_from_beta()
        r_at_40 = counts_to_resistance(temp_to_counts(40.0))

        self.assertAlmostEqual(
            resistance_to_temp_steinhart(r_at_40, coeffs),
            resistance_to_temp_beta(r_at_40),
            delta=0.5,
        )

    def test_rejects_wrong_number_of_points(self):
        with self.assertRaises(ValueError):
            solve_steinhart_hart([(10_000.0, 25.0), (5_000.0, 45.0)])

    def test_rejects_narrow_temperature_span(self):
        """Three points at nearly the same temperature can't define a curve.
        Refuse loudly rather than emit garbage coefficients that would then
        silently corrupt every future reading."""
        points = [
            (10_000.0, 25.0),
            (10_001.0, 25.001),
            (10_002.0, 25.002),
        ]
        with self.assertRaisesRegex(ValueError, "span"):
            solve_steinhart_hart(points)

    def test_rejects_singular_matrix_despite_wide_span(self):
        """Wide temperature span, but two points report the same resistance —
        physically impossible, and the 3x3 solve is degenerate. The span check
        passes here, so the determinant backstop has to catch it."""
        points = [
            (10_000.0, 0.0),
            (10_000.0, 25.0),  # same resistance, very different temperature
            (3_600.0, 50.0),
        ]
        with self.assertRaisesRegex(ValueError, "singular"):
            solve_steinhart_hart(points)

    def test_rejects_non_physical_calibration_resistance(self):
        with self.assertRaises(ValueError):
            solve_steinhart_hart([(0.0, 0.0), (10_000.0, 25.0), (3_600.0, 50.0)])


class TestRoundTrip(unittest.TestCase):
    def test_temp_to_counts_and_back(self):
        """The sim fakes raw counts; production math converts them back. If
        this round-trip drifts, the simulator is lying to us."""
        for temp_c in (5.0, 20.0, 25.0, 40.0, 60.0, 80.0):
            counts = temp_to_counts(temp_c)
            recovered = resistance_to_temp_beta(counts_to_resistance(counts))
            # 10-bit quantization is the only loss here.
            self.assertAlmostEqual(recovered, temp_c, delta=0.6)

    def test_counts_stay_in_adc_range(self):
        """Even absurd temperatures must never produce out-of-range counts."""
        for temp_c in (-40.0, 150.0):
            counts = temp_to_counts(temp_c)
            self.assertGreaterEqual(counts, 1)
            self.assertLessEqual(counts, ADC_MAX_COUNTS - 1)


class TestThermistorSensor(unittest.TestCase):
    def test_reads_simulated_channels(self):
        adc = SimAdc({0: 42.0, 1: 30.0})
        sensor = ThermistorSensor(adc=adc, channels=[0, 1])

        readings = sensor.read()

        self.assertEqual(len(readings), 2)
        self.assertEqual(readings[0].probe_id, "thermistor-ch0")
        self.assertEqual(readings[0].source, "thermistor")
        self.assertAlmostEqual(readings[0].temp_c, 42.0, delta=0.6)
        self.assertAlmostEqual(readings[1].temp_c, 30.0, delta=0.6)

    def test_unwired_channel_is_skipped_not_faked(self):
        """Channel 2 has no probe. The sensor must omit it — never invent a
        reading for hardware that isn't there."""
        adc = SimAdc({0: 42.0})
        sensor = ThermistorSensor(adc=adc, channels=[0, 2])

        readings = sensor.read()

        self.assertEqual(len(readings), 1)
        self.assertEqual(readings[0].probe_id, "thermistor-ch0")

    def test_all_channels_dead_returns_empty(self):
        """The agent treats an empty list as 'no data this cycle' and posts
        nothing, rather than posting a fabricated reading."""
        sensor = ThermistorSensor(adc=SimAdc({}), channels=[0, 1])
        self.assertEqual(sensor.read(), [])


if __name__ == "__main__":
    unittest.main()
